In [17]:
#Wikipedia scraping for Toronto postal codes
import pandas as pd
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
df_scrape = pd.read_html(url)

In [18]:
#check number of tables found
len(df_scrape)

3

In [19]:
#show table
df_scrape[0].head()

  Postal Code           Borough              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

In [20]:
#create separate dataframe
df_post_code = df_scrape[0]
df_post_code.head()

  Postal Code           Borough              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

In [21]:
#remove rows with borough Not assigned

# Get names of indexes
indexNames = df_post_code[ df_post_code['Borough'] == 'Not assigned' ].index

# Delete these row indexes from dataFrame
df_post_code.drop(indexNames , inplace=True)
df_post_code.head()

  Postal Code           Borough                                Neighbourhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [22]:
# More than one neighborhood can exist in one postal code area, combined these into one row with the neighborhoods separated with a comma
df_post_code["Neighbourhood"] = df_post_code.groupby("Postal Code")["Neighbourhood"].transform(lambda neigh: ', '.join(neigh))

#remove duplicates
df_post_code = df_post_code.drop_duplicates()

#update index to be Postal Code if it isn't already
#if(df_post_code.index.name != 'Postal Code'):
#    df_post_code = df_post_code.set_index('Postal Code')
    
df_post_code.head()

  Postal Code           Borough                                Neighbourhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [23]:
#if a cell has a borough but a Not assigned  neighborhood, then the neighborhood will be the same as the borough
indexNames = df_post_code['Neighbourhood'] == 'Not assigned'
df_post_code['Neighbourhood'][indexNames] = df_post_code['Borough'][indexNames]
df_post_code.head()

  Postal Code           Borough                                Neighbourhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [24]:
#in the last cell of your notebook, use the .shape method to print the number of rows of your dataframe
df_post_code.shape

(103, 3)